name: Publish release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    uses: wphillipmoore/standard-actions/.github/workflows/publish-release.yml@develop
    permissions:
      contents: write
      pull-requests: write
    with:
      ecosystem: none
      version-command: cat VERSION
      release-title: mq-rest-admin-common
      release-notes: |
        ## Links

        - [Documentation](https://wphillipmoore.github.io/mq-rest-admin-common/)
      version-file: VERSION
      version-regex: '(.*)'
      version-replacement: '{version}'
      develop-version-command: cat
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
